apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "future-water.fullname" . }}-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.data.size }}
  storageClassName: {{ .Values.data.storageClassname }}
  volumeMode: Filesystem
