apiVersion: v1
kind: Service
metadata:
  name: {{ include "future-water.fullname" . }}
  labels:
    {{- include "future-water.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-fw
      protocol: TCP
      name: http-fw
  selector:
    {{- include "future-water.selectorLabels" . | nindent 4 }}
