apiVersion: batch/v1
kind: Job
metadata:
  name: initial-data
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: initial-data
        image: {{ .Values.dataIngestion.initialData }}
        env:
        - name: URL
          value: geoserver.{{ .Values.ingress.host }}/geoserver
        - name: PDFS_URL
          value: {{ .Values.dataIngestion.pdfsUrl }}        
        - name: GEOSERVER_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "geoserver.secretName" . }}
              key: geoserver-user
        - name: GEOSERVER_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "geoserver.secretName" . }}
              key: geoserver-password              
  backoffLimit: 4