{{- if .Values.dataIngestionDW.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: initial-data
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: initial-data
        image: {{ .Values.dataIngestionDW.initialData }}
        imagePullPolicy: {{ .Values.dataIngestionDW.pullPolicy }}        
        env:
        - name: URL
          value: {{ template "geoserver.fullname" . }}{{ .Values.ingress.path }}
        - name: PDFS_URL_GROUNDWATER
          value: {{ .Values.dataIngestionDW.pdfsUrlGW }}
        - name: PDFS_URL_SURFACEWATER
          value: {{ .Values.dataIngestionDW.pdfsUrlSW }}
        - name: PDFS_URL_NITRATE
          value: {{ .Values.dataIngestionDW.pdfsUrlNVZ }}
        - name: GEOSERVER_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "geoserver.secretName" . }}
              key: geoserver-user
        - name: GEOSERVER_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "geoserver.secretName" . }}
              key: geoserver-password              
  backoffLimit: 4
{{- end }}
