{{- if .Values.persistence.blob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rpa-index-deployment
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: rpa-index
            image: {{ .Values.dataIngestionRPA.rpaData }}
            env:
            - name: URL
              value: {{ template "geoserver.fullname" . }}{{ .Values.ingress.path }}
            - name: WORKSPACE
              value: {{ .Values.dataIngestionRPA.workspace }}
            - name: DATASTORE
              value: {{ .Values.dataIngestionRPA.datastore }}
            - name: DATA_DIR
              value: {{ .Values.dataIngestionRPA.dataDir }}
            - name: BLOB_DIR
              value: {{ .Values.dataIngestionRPA.blobDir }}
            - name: GEOSERVER_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "geoserver.secretName" . }}
                  key: geoserver-user
            - name: GEOSERVER_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "geoserver.secretName" . }}
                  key: geoserver-password    
            volumeMounts:
              - name: blob01
                mountPath: {{ .Values.dataIngestionRPA.blobDir }}
              - name: geoserver-data-dir
                mountPath: {{ .Values.dataIngestionRPA.dataDir }}
                subPath: {{ .Values.persistence.geoserverDataDir.subPath }}
          volumes:
            - name: blob01
              persistentVolumeClaim:
                claimName: {{ template "geoserver.fullname" . }}-rpa-blob
{{- if and .Values.persistence.geoserverDataDir.enabled .Values.persistence.geoserverDataDir.existingClaim }}
            - name: geoserver-data-dir
              persistentVolumeClaim:
{{- with .Values.persistence.geoserverDataDir.existingClaim }}
                claimName: {{ tpl . $ }}
{{- end }}
{{- else if .Values.persistence.geoserverDataDir.enabled }}
            - name: geoserver-data-dir
              persistentVolumeClaim:
                claimName: {{ template "geoserver.fullname" . }}-geoserver-data-dir
{{- else if not .Values.persistence.geoserverDataDir.enabled }}
            - name: geoserver-data-dir
              emptyDir: {}
{{- end }}
{{- end }}
