apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "defra-smp.fullname" . }}
  labels:
    app: {{ template "defra-smp.fullname" . }}
    chart: {{ template "defra-smp.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- with .Values.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
data:
  reverse-proxy.conf: |
    server {
          location / {
                    rewrite ^/$ /shoreline-planning redirect;
          }
          location /shoreline-planning {
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header Host $host;
                    proxy_set_header X-NginX-Proxy true;
                    proxy_set_header X-Forwarded-Proto $scheme;#
                    add_header 'Content-Security-Policy' 'upgrade-insecure-requests';
                    proxy_pass http://{{ include "defra-smp.fullname" . }}-web:3001/shoreline-planning;
                    add_header Access-Control-Allow-Origin *;
            }
            location /shoreline-planning/zxy {
                    add_header Access-Control-Allow-Origin *;
                    alias /opt/defra-smp/assets/zxy ;
            }
            location /shoreline-planning/documents {
                    add_header Access-Control-Allow-Origin *;
                    alias /opt/defra-smp/assets/documents ;
            }
    }
    

