{{- if .Values.processor.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "defra-smp.fullname" . }}-processor
  labels:
    app: {{ include "defra-smp.fullname" . }}-processor
spec:
  selector:
    matchLabels:
      app: {{ include "defra-smp.fullname" . }}-processor
  schedule: {{ .Values.processor.cronjobExpression }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: {{ include "defra-smp.fullname" . }}-data
              image: "{{ .Values.processor.imageData.repository }}:{{ .Values.processor.imageData.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.processor.imageData.pullPolicy }}
              resources:
                {{- toYaml .Values.processor.resources | nindent 16 }}
              env:
              - name: ENVIRONMENT
                value: {{ .Values.processor.environment }}
              - name: DB_URL
                value: {{ include "defra-smp.fullname" . }}-db                
              - name: CONTAINER_NAME
                valueFrom:
                  secretKeyRef:
                    name: {{ template "defra-smp.secretName" . }}
                    key: CONTAINER_NAME   
              - name: ACCOUNT_NAME
                valueFrom:
                  secretKeyRef:
                    name: {{ template "defra-smp.secretName" . }}
                    key: ACCOUNT_NAME
              - name: SAS_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: {{ template "defra-smp.secretName" . }}
                    key: SAS_TOKEN
              volumeMounts:
                - mountPath: /opt/output
                  name: tiles
                  subPath: {{ .Values.processor.data.subpath }}/zxy                           
          initContainers:
            - name: {{ include "defra-smp.fullname" . }}-tile
              image: "{{ .Values.processor.imageTile.repository }}:{{ .Values.processor.imageTile.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.processor.imageTile.pullPolicy }}
              env:
              - name: ENVIRONMENT
                value: {{ .Values.processor.environment }} 
              - name: BASE_PATH
                value: /var/opt/tile-loader                     
              - name: CONTAINER_NAME
                valueFrom:
                  secretKeyRef:
                    name: {{ template "defra-smp.secretName" . }}
                    key: CONTAINER_NAME   
              - name: ACCOUNT_NAME
                valueFrom:
                  secretKeyRef:
                    name: {{ template "defra-smp.secretName" . }}
                    key: ACCOUNT_NAME
              - name: SAS_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: {{ template "defra-smp.secretName" . }}
                    key: SAS_TOKEN                
              - name: AGRIMETRICS_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ template "defra-smp.secretName" . }}
                    key: AGRIMETRICS_API_KEY              
              resources:
                {{- toYaml .Values.processor.resources | nindent 16 }}
              volumeMounts:
                - mountPath: /var/opt/tile-loader/output
                  name: tiles
                  subPath: {{ .Values.processor.data.subpath }}/zxy
          volumes:
            - name: tiles
              persistentVolumeClaim:
                claimName: {{ include "defra-smp.fullname" . }}-tiles
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.processor.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.processor.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
{{- end }}
