{{- if .Values.nginx.ingress.enabled -}}
{{- $fullName := include "defra-smp.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.nginx.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.nginx.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.nginx.ingress.annotations "kubernetes.io/ingress.class" .Values.nginx.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-nginx
  labels:
    {{- include "defra-smp.labels" . | nindent 4 }}
  {{- with .Values.nginx.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.nginx.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.nginx.ingress.className }}
  {{- end }}
  {{- if .Values.nginx.ingress.tls }}
  tls:
    - hosts:
        {{- range .Values.hosts }}
        - {{ .host }}
        {{- end }}
      secretName: {{ include "defra-smp.fullname" $ }}-nginx-tls
  {{- end }}
  rules:
    {{- range .Values.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /shoreline-planning(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-nginx
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
    {{- end }}
{{- end }}