{{- if .Values.processor.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: initial-data
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: initial-data
        image: "{{ .Values.processor.documentData.repository }}:{{ .Values.processor.documentData.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.processor.documentData.pullPolicy }}        
        env:
          - name: ENVIRONMENT
            value: {{ .Values.processor.environment }}
          - name: DB_URL
            value: {{ include "defra-smp.fullname" . }}-db
          - name: CONTAINER_NAME
            valueFrom:
              secretKeyRef:
                name: {{ template "defra-smp.secretName" . }}
                key: CONTAINER_NAME   
          - name: ACCOUNT_NAME
            valueFrom:
              secretKeyRef:
                name: {{ template "defra-smp.secretName" . }}
                key: ACCOUNT_NAME
          - name: SAS_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ template "defra-smp.secretName" . }}
                key: SAS_TOKEN
        volumeMounts:
          - mountPath: /opt/defra-smp/assets
            name: tiles
            subPath: {{ .Values.processor.data.subpath }}/documents
      volumes:
        - name: tiles
          persistentVolumeClaim:
            claimName: {{ include "defra-smp.fullname" . }}-tiles          
{{- end }}
