apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "defra-smp.fullname" . }}-databases
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: {{ .Values.fuseki.data.storageClassName }}
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "defra-smp.fullname" . }}-tiles
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: {{ .Values.processor.data.storageClassName }}
  volumeMode: Filesystem