{{- if not .Values.processor.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "defra-smp.secretName" . }}
type: Opaque
data:
  AGRIMETRICS_API_KEY: changeme
  SAS_TOKEN: changeme
  CONTAINER_NAME: changeme
  ACCOUNT_NAME: changeme
{{- end }}
