apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "defra-dfm.fullname" . }}-app
  labels:
    app: {{ include "defra-dfm.fullname" . }}-app
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "defra-dfm.fullname" . }}-app
  template:
    metadata:
      labels:
        app: {{ include "defra-dfm.fullname" . }}-app
    spec:
      containers:
      - name: {{ include "defra-dfm.fullname" . }}-app
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        ports:
          - containerPort: 3000
            name: http-app
        resources:
          {{- toYaml .Values.app.resources | nindent 12 }}
        env:
          - name: DFM_QUERY_ENDPOINT
            value: http://{{ include "defra-dfm.fullname" . }}-db:7200/repositories/data-flow-mapper
          - name: DFM_UPDATE_ENDPOINT
            value: http://{{ include "defra-dfm.fullname" . }}-db:7200/repositories/data-flow-mapper            
          - name: DFM_AUTH0_CALLBACK_URL
            value: {{ .Values.app.auth.callbackUrl }}              
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "defra-dfm.fullname" . }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "defra-dfm.fullname" . }}-db
  strategy:
    type: Recreate
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: {{ include "defra-dfm.fullname" . }}-db
    spec:
      containers:
        - image: "{{ .Values.graphdb.image.repository }}:{{ .Values.graphdb.image.tag }}"
          args:
          {{ range .Values.graphdb.args }}
            - {{ . }}
          {{ end }}
          imagePullPolicy: {{ .Values.graphdb.image.pullPolicy }}
          name: {{ include "defra-dfm.fullname" . }}-db
          ports:
            - containerPort: 7200
              protocol: TCP
          resources:
            {{- toYaml .Values.graphdb.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:   
            - mountPath: /opt/graphdb/home/graphdb-import
              name: graphdb-import
              subPath: cde/{{ .Values.release }}/{{ .Values.graphdb.import.subpath }}
            - mountPath: /opt/graphdb/dist/data/repositories
              name: graphdb-databases
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      {{- with .Values.graphdb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.graphdb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}      
      volumes:
        - name: graphdb-import
          persistentVolumeClaim:
            claimName: {{ include "defra-dfm.fullname" . }}-import
        - name: graphdb-databases
          persistentVolumeClaim:
            claimName: {{ include "defra-dfm.fullname" . }}-databases