{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "defra-dfm.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx    
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/proxy-body-size: '0'
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
  labels:
    app: {{ include "defra-dfm.fullname" . }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: data-flow-mapping.{{ .host }}
    http:
      paths:
      - backend:
          service: 
            name: {{ include "defra-dfm.fullname" $ }}-app
            port: 
              number: 80
        path: (/|$)(.*)
        pathType: Prefix
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ .host }}
        {{- end }}
      secretName: {{ include "defra-dfm.fullname" . }}-app-tls
  {{- end }}
{{- end }}
