---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "defra-dfm.fullname" . }}-logs-{{ .Values.release }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: {{ .Values.graphdb.storageClassName }}
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "defra-dfm.fullname" . }}-databases-{{ .Values.release }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: {{ .Values.graphdb.storageClassName }}
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "defra-dfm.fullname" . }}-import-{{ .Values.release }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: {{ .Values.graphdb.import.storageClassName }}
  volumeMode: Filesystem
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ include "defra-dfm.fullname" . }}-cache-blob-{{ .Values.release }}
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: {{ .Values.cache.size }}
#   storageClassName: {{ .Values.cache.storageClassname }}
# ---   