apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "defra-dfm.fullname" . }}-app
  name: {{ include "defra-dfm.fullname" . }}-app
spec:
  ports:
    - name: http-app
      port: 3000
      protocol: TCP
      targetPort: http-app
  selector:
    app: {{ include "defra-dfm.fullname" . }}-app
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "defra-dfm.fullname" . }}-db
  name: {{ include "defra-dfm.fullname" . }}-db
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 7200
      protocol: TCP
      targetPort: 7200
  selector:
    app: {{ include "defra-dfm.fullname" . }}-db
  sessionAffinity: None
  type: ClusterIP