apiVersion: v1
kind: Service
metadata:
  name: {{ include "biodiversity-net-gain.fullname" . }}
  labels:
    {{- include "biodiversity-net-gain.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.staticApp.vhost }}
