{{- if .Values.cache.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: initial-data-{{ .Values.release }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: cache-data
        image: "{{ .Values.cache.image.repository }}:{{ .Values.cache.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.cache.image.pullPolicy }}        
        env:
          - name: API_ENDPOINT
            value: {{ .Values.graphEndpoint }}
        volumeMounts:
          - name: cache
            mountPath: /opt/files
            subPath: cde/test/blue
            # subPath: cde/test/{{ .Values.release }}
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: {{ include "defra-cde.fullname" . }}-cache-{{ .Values.release }}                       
{{- end }}
