apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "defra-cde.fullname" . }}-app-{{ .Values.release }}
  labels:
    app: {{ include "defra-cde.fullname" . }}-app-{{ .Values.release }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "defra-cde.fullname" . }}-app-{{ .Values.release }}
  template:
    metadata:
      labels:
        app: {{ include "defra-cde.fullname" . }}-app-{{ .Values.release }}
    spec:
      containers:
      - name: {{ include "defra-cde.fullname" . }}-app
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        ports:
          - containerPort: 3000
            name: http-app
        resources:
          {{- toYaml .Values.app.resources | nindent 12 }}
        env:
          - name: GDB_ENDPOINT_COLOUR
            value: {{ .Values.release }}
        volumeMounts:
          - name: cache
            mountPath: /app/classpath
            subPath: cde/{{ .Values.release }}
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: {{ include "defra-cde.fullname" . }}-cache-blob-{{ .Values.release }}                        
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # volumes:
      #   - name: data
      #     persistentVolumeClaim:
      #       claimName: {{ include "defra-cde.fullname" . }}-data-blob
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "defra-cde.fullname" . }}-db-{{ .Values.release }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "defra-cde.fullname" . }}-db-{{ .Values.release }}
  strategy:
    type: Recreate
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: {{ include "defra-cde.fullname" . }}-db-{{ .Values.release }}
    spec:
      containers:
        - image: "{{ .Values.graphdb.image.repository }}:{{ .Values.graphdb.image.tag }}"
          args: ["-XX:MaxRAMPercentage=70", "-Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import"]
          imagePullPolicy: {{ .Values.graphdb.image.pullPolicy }}
          name: {{ include "defra-cde.fullname" . }}-db
          ports:
            - containerPort: 7200
              protocol: TCP
          resources:
            {{- toYaml .Values.graphdb.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/graphdb/dist/logs
              name: graphdb-logs          
            - mountPath: /opt/graphdb/home/graphdb-import
              name: graphdb-import
            - mountPath: /opt/graphdb/dist/data/repositories
              name: graphdb-databases
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      {{- with .Values.graphdb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.graphdb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}      
      volumes:
        - name: graphdb-import
          persistentVolumeClaim:
            claimName: {{ include "defra-cde.fullname" . }}-import-{{ .Values.release }}
        - name: graphdb-logs
          persistentVolumeClaim:
            claimName: {{ include "defra-cde.fullname" . }}-logs-{{ .Values.release }}
        - name: graphdb-databases
          persistentVolumeClaim:
            claimName: {{ include "defra-cde.fullname" . }}-databases-{{ .Values.release }}