{{- if .Values.varnish.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "defra-cde.fullname" . }}-varnish-{{ .Values.release }}
  annotations:
    kubernetes.io/ingress.class: nginx    
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/proxy-body-size: '0'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: htpasswd
    nginx.ingress.kubernetes.io/auth-realm: "Enter your credentials"    
    nginx.ingress.kubernetes.io/server-snippet: |
      gzip on;
      gzip_http_version 1.0;
      gzip_proxied any;
      gzip_min_length 500;
      gzip_disable "MSIE [1-6]\.";
      gzip_types text/plain text/html text/xml text/css
                text/comma-separated-values text/csv
                text/javascript application/x-javascript
                application/atom+xml application/json
                application/n-triples;
      proxy_hide_header Access-Control-Allow-Origin;
      proxy_hide_header X-Powered-By;
      proxy_hide_header X-Runtime;
      server_tokens off;
      proxy_cookie_path /catchment-planning "/; SameSite=none";

  labels:
    app: {{ include "defra-cde.fullname" . }}-varnish-{{ .Values.release }}
spec:
  rules:
  {{- range .Values.varnish.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      - backend:
          service: 
            name: {{ include "defra-cde.fullname" $ }}-varnish-{{ $.Values.release }}
            port: 
              number: 80
        path: /catchment-planning(/|$)(.*)
        pathType: Prefix
  {{- end }}
  {{- if .Values.varnish.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.varnish.ingress.hosts }}
        - {{ .host }}
        {{- end }}
      secretName: {{ include "defra-cde.fullname" . }}-varnish-tls
  {{- end }}
{{- end }}
