---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "defra-cde.fullname" . }}-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: {{ .Values.graphdb.storageClassName }}
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "defra-cde.fullname" . }}-databases
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: {{ .Values.graphdb.storageClassName }}
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "defra-cde.fullname" . }}-import
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: {{ .Values.graphdb.import.storageClassName }}
  volumeMode: Filesystem    