---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "defra-cde.fullname" . }}-logs-{{ .Values.release }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: {{ .Values.graphdb.storageClassName }}
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "defra-cde.fullname" . }}-databases-{{ .Values.release }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: {{ .Values.graphdb.storageClassName }}
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "defra-cde.fullname" . }}-import-{{ .Values.release }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: {{ .Values.graphdb.import.storageClassName }}
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "defra-cde.fullname" . }}-cache-{{ .Values.release }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.cache.size }}
  storageClassName: {{ .Values.cache.storageClassname }}
---   