apiVersion: v1
kind: Service
metadata:
  name: {{ include "defra-cde.fullname" . }}-varnish-{{ .Values.release }}
  labels:
    {{- include "defra-cde.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    app: {{ include "defra-cde.fullname" . }}-varnish-{{ .Values.release }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "defra-cde.fullname" . }}-app-{{ .Values.release }}
  name: {{ include "defra-cde.fullname" . }}-app-{{ .Values.release }}
spec:
  ports:
    - name: http-app
      port: 3000
      protocol: TCP
      targetPort: http-app
  selector:
    app: {{ include "defra-cde.fullname" . }}-app-{{ .Values.release }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "defra-cde.fullname" . }}-db-{{ .Values.release }}
  name: {{ include "defra-cde.fullname" . }}-db-{{ .Values.release }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 7200
      protocol: TCP
      targetPort: 7200
  selector:
    app: {{ include "defra-cde.fullname" . }}-db-{{ .Values.release }}
  sessionAffinity: None
  type: ClusterIP