apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rpa-land-parcels.fullname" . }}
  labels:
    app: {{ template "rpa-land-parcels.fullname" . }}
    chart: {{ template "rpa-land-parcels.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- with .Values.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
data:
  init-mongo.sh: |
    set -e

    mongosh <<EOF
    use $MONGO_INITDB_DATABASE

    db.createUser({
        user:'$MONGO_INITDB_ROOT_USERNAME',
        pwd: '$MONGO_INITDB_ROOT_PASSWORD',
        roles:[{
            role:'readWrite',
            db: '$MONGO_INITDB_DATABASE'
        }]
    })
    EOF
  {{- with .Values.extraConfigMap }}
  {{- tpl . $ | nindent 2 }}
  {{- end }}
