apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  storageClassName: "azurefile-retain"
  accessModes:
    - ReadWriteMany
  volumeName:
  resources:
    requests:
      storage: 1Gi
