{{- if or (not .Values.existingSecret) .Values.extraSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rpa-land-parcels.secretName" . }}
  labels:
    app: {{ template "rpa-land-parcels.fullname" . }}
    chart: {{ template "rpa-land-parcels.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if not .Values.existingSecret }}
  user: {{ .Values.mongoUser | b64enc | quote }}
  password: {{ include "rpa-land-parcels.password" . | b64enc | quote }}
  apiKey: {{ include "rpa-land-parcels.apiKey" . | b64enc | quote }}
  {{- end }}
  {{- with .Values.extraSecret }}
  {{- tpl . $ | nindent 2 }}
  {{- end }}
{{- end }}
