apiVersion: v1
kind: Service
metadata:
  name: {{ include "rpa-land-parcels.fullname" . }}
  labels:
    {{- include "rpa-land-parcels.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-rpa
      protocol: TCP
      name: http-rpa
  selector:
    {{- include "rpa-land-parcels.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}-db
  name: {{ .Chart.Name }}-db
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: http-rpa-db
  selector:
    app: {{ .Chart.Name }}-db
status:
  loadBalancer: {}