apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "defra-wims.fullname" . }}
  labels:
    app: {{ template "defra-wims.fullname" . }}
    chart: {{ template "defra-wims.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- with .Values.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
data:
  app.conf: |
    # app configuration

    # Plugin extension for velocity library
    apix                 = com.epimorphics.simpleAPI.webapi.LibAPI

    # Velocity engine
    velocity             = com.epimorphics.appbase.templates.VelocityRender
    velocity.templates   = {webapp}/WEB-INF/templates
    #velocity.templates   = /opt/epr/templates
    velocity.root        = /ui
    velocity.production  = false
    velocity.plugin      = $apix

    # Real data source
    ssource              = com.epimorphics.appbase.data.impl.RemoteSparqlSource
    ssource.endpoint     = {{ .Values.api.appConfig.ssourceEndpoint }}

    dsource              = com.epimorphics.simpleAPI.query.impl.SparqlDataSource
    dsource.source       = $ssource

    # Set up default prefixes
    prefixes             = com.epimorphics.appbase.core.PrefixService
    prefixes.prefixFile  = {webapp}/WEB-INF/prefixes.ttl

    # handle transform setup
    # spatial = com.epimorphics.sparql.geo.GeoTransformByJenaSpatial
    spatial = com.epimorphics.sparql.geo.GeoTransformBySparqlFilter
    apptransforms         = com.epimorphics.simpleAPI.queryTransforms.AppTransforms
    apptransforms.include = $spatial

    # Request processors to support generic geo and start queries
    geoProc    = com.epimorphics.simpleAPI.requests.GeoRequestProcessor

    searchProc = com.epimorphics.simpleAPI.requests.SearchRequestProcessor
    searchProc.filterDistinct = true

    # Cache manager for batch results
    cache                = com.epimorphics.armlib.impl.FileCacheManager
    cache.cacheDir       = /tmp/wims/
    cache.urlPrefix      = /water-quality/batch/result-download/
    cache.defaultSuffix  = csv
    cache.compressed     = true

    #cache                = com.epimorphics.armlib.impl.S3CacheManager
    #cache.bucket         = environment-open-data
    #cache.baseKey        = wims
    #cache.compressed     = true

    # Queue manager for batch preparation
    queue                = com.epimorphics.armlib.impl.MemQueueManager
    #queue                = com.epimorphics.armlib.impl.DynQueueManager
    #queue.checkInterval  = 1500

    # Batch Data source
    bssource              = com.epimorphics.appbase.data.impl.RemoteSparqlSource
    bssource.endpoint     = {{ .Values.api.appConfig.bsourceEndpoint }}
    bssource.connectTimeout = 10000
    bssource.remoteTimeout = 36000000

    batchSource              = com.epimorphics.simpleAPI.query.impl.SparqlDataSource
    batchSource.source       = $bssource

    # Batch request manager
    reqm                 = com.epimorphics.armlib.impl.StandardRequestManager
    reqm.cacheManager    = $cache
    reqm.queueManager    = $queue

    # Batch processor
    batch                = com.epimorphics.wims.batch.BatchProcessor
    batch.requestManager = $reqm
    batch.source         = $batchSource

    # Additional config
    config               = com.epimorphics.appbase.core.GenericConfig
    config.lastDate = 2015
    config.firstDate = 2005
    config.gtagUACode = g-tag-ua-code

    # Set the API key for the OS maps API here
    config.osMapsAPIKey =

    # API configuration
    api                  = com.epimorphics.simpleAPI.core.API
    api.source           = $dsource
    api.baseURI          = {{ .Values.api.appConfig.baseUrl }}
    api.documentation    = {{ .Values.api.appConfig.documentationUrl }}
    api.publisher        = Environment Agency
    api.licence          = http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/
    api.contextURL       = {{ .Values.api.appConfig.contextUrl }}
    api.comment          = WARNING: Pre-alpha test service
    api.endpointSpecDir  = {webapp}/WEB-INF/endpointSpecs
    api.maxAge           = 86400
    api.showLangTag      = false
    api.fullPathsInCSVHeaders = true
    api.requestProcessors = $geoProc, $searchProc
    api.defaultItemTemplate = genericItem.vm
    api.defaultListTemplate = genericList.vm
    api.htmlNonDefault      = true
    api.configExtensions = $config



