apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "defra-wims.fullname" . }}-db
  labels:
    app: {{ include "defra-wims.fullname" . }}-db
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ include "defra-wims.fullname" . }}-db
  template:
    metadata:
      labels:
        app: {{ include "defra-wims.fullname" . }}-db
    spec:
      containers:
        - name: {{ include "defra-wims.fullname" . }}-db
          image: "{{ .Values.fuseki.image.repository }}:{{ .Values.fuseki.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.fuseki.image.pullPolicy }}
          ports:
            - containerPort: 3030
              name: http-wims-db
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          volumeMounts:
            - name: fuseki-logs
              mountPath: /fuseki/logs
            - name: fuseki-databases
              mountPath: /fuseki/databases
            - name: processor-work
              mountPath: /var/lib/wims-staging
      volumes:
        - name: fuseki-logs
          persistentVolumeClaim:
            claimName: {{ include "defra-wims.fullname" . }}-logs
        - name: fuseki-databases
          persistentVolumeClaim:
            claimName: {{ include "defra-wims.fullname" . }}-databases
        - name: processor-work
          persistentVolumeClaim:
            claimName: {{ include "defra-wims.fullname" . }}-work
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "defra-wims.fullname" . }}-api
  labels:
    app: {{ include "defra-wims.fullname" . }}-api
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ include "defra-wims.fullname" . }}-api
  template:
    metadata:
      labels:
        app: {{ include "defra-wims.fullname" . }}-api
    spec:
      containers:
        - name: {{ include "defra-wims.fullname" . }}-api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http-wims-api
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "defra-wims.secretName" . }}
                  key: awsAccessKeyId
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "defra-wims.secretName" . }}
                  key: awsSecretAccessKey
          volumeMounts:
            - name: api-config
              mountPath: /etc/api
              readOnly: true
            - mountPath: /opt/cache
              name: cache
              subPath: {{ .Values.fuseki.cache.subpath }}
            - name: processor-work
              mountPath: /var/lib/wims-staging
      volumes:
        - name: api-config
          configMap:
            name: {{ template "defra-wims.fullname" . }}
            defaultMode: 0644
            items:
              - key: app.conf
                path: app.conf
        - name: cache
          persistentVolumeClaim:
            claimName: {{ include "defra-wims.fullname" . }}-cache
        - name: processor-work
          persistentVolumeClaim:
            claimName: {{ include "defra-wims.fullname" . }}-work
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "defra-wims.fullname" . }}-ui
  labels:
    app: {{ include "defra-wims.fullname" . }}-ui
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ include "defra-wims.fullname" . }}-ui
  template:
    metadata:
      labels:
        app: {{ include "defra-wims.fullname" . }}-ui
    spec:
      containers:
        - name: {{ include "defra-wims.fullname" . }}-ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http-wims-ui
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          env:
            - name: API_HOST
              value: http://{{ include "defra-wims.fullname" . }}-varnish:8888
            - name: GOOGLE_ANALYTICS_ID
              value: {{ .Values.googleAnalyticsId }}
            - name: OS_API_KEY
              value: {{ .Values.osMapsAPIKey }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "defra-wims.fullname" . }}-varnish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "defra-wims.fullname" . }}-varnish
  strategy:
    type: Recreate
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: {{ include "defra-wims.fullname" . }}-varnish
    spec:
      containers:
        - image: "varnish:7.4.2"
          command: ["varnishd"]
          args: ["-F", "-a", ":8888", "-f", "/etc/varnish/default.vcl", "-s", "file,/var/lib/varnish/varnish_storage.bin,20G"]
          name: {{ include "defra-wims.fullname" . }}-varnish
          ports:
            - containerPort: 8888
              protocol: TCP
          resources:
            {{- toYaml .Values.varnish.resources | nindent 12 }}
          volumeMounts:
            - name: varnish-config
              mountPath: /etc/varnish
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      {{- with .Values.varnish.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.varnish.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: varnish-config
          configMap:
            name: {{ template "defra-wims.fullname" . }}
            defaultMode: 0644
            items:
              - key: default.vcl
                path: default.vcl
