{{- if .Values.api.ingress.enabled -}}
{{- $fullName := include "defra-wims.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.api.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.api.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.api.ingress.annotations "kubernetes.io/ingress.class" .Values.api.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-api-{{ .Values.release }}
  labels:
    {{- include "defra-wims.labels" . | nindent 4 }}
  {{- with .Values.api.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.api.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.api.ingress.className }}
  {{- end }}
  {{- if .Values.api.ingress.tls }}
  tls:
    {{- range .Values.api.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ include "defra-wims.fullname" $ }}-api-tls
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.api.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-api-{{ $.Values.release }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}

---
{{- if .Values.fuseki.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "defra-wims.fullname" . }}-fuseki-{{ .Values.release }}
  labels:
    app: {{ include "defra-wims.fullname" . }}-fuseki-{{ .Values.release }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/proxy-body-size: '0'
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
spec:
  {{- if .Values.fuseki.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.fuseki.ingress.hosts }}
        - {{ .host }}
        {{- end }}
      secretName: {{ include "defra-wims.fullname" $ }}-fuseki-tls
  {{- end }}
  rules:
    {{- range .Values.fuseki.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: /fuseki-db
            pathType: Prefix
            backend:
              service:
                name: {{ include "defra-wims.fullname" $ }}-fuseki-{{ $.Values.release }}
                port:
                  number: 80
    {{- end }}
{{- end }}

---
{{- if .Values.ui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "defra-wims.fullname" . }}-ui-{{ .Values.release }}
  labels:
    {{- include "defra-wims.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ui.ingress.tls.enabled }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{- end }}
    ingress.kubernetes.io/proxy-body-size: '0'
    ingress.kubernetes.io/ssl-redirect: 'true'
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
spec:
  rules:
    {{- range .Values.ui.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
        - path: /water-quality/view(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ include "defra-wims.fullname" $ }}-ui-{{ $.Values.release }}
              port:
                number: 80
    {{- end }}
{{- end }}
