apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "defra-wims.fullname" . }}-logs
  labels:
    app: {{ include "defra-wims.fullname" . }}
    instance: {{ include "defra-wims.fullname" . }}-db
    role: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: {{ .Values.fuseki.data.storageClassName }}
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "defra-wims.fullname" . }}-databases
  labels:
    app: {{ include "defra-wims.fullname" . }}
    instance: {{ include "defra-wims.fullname" . }}-db.{{ include "defra-wims.fullname" . }}-processor
    role: database, processor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: {{ .Values.fuseki.data.storageClassName }}
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "defra-wims.fullname" . }}-cache
  labels:
    app: {{ include "defra-wims.fullname" . }}
    instance: {{ include "defra-wims.fullname" . }}-api.{{ include "defra-wims.fullname" . }}-processor
    role: api, processor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: {{ .Values.fuseki.cache.storageClassName }}
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "defra-wims.fullname" . }}-work
  labels:
    app: {{ include "defra-wims.fullname" . }}
    instance: {{ include "defra-wims.fullname" . }}-api.{{ include "defra-wims.fullname" . }}-db.{{ include "defra-wims.fullname" . }}-processor
    role: api, database, processor  
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi
  storageClassName: {{ .Values.fuseki.cache.storageClassName }}
  volumeMode: Filesystem
