{{- if or (not .Values.existingSecret) .Values.extraSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "defra-wims.secretName" . }}
  labels:
    app: {{ template "defra-wims.fullname" . }}
    chart: {{ template "defra-wims.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if not .Values.existingSecret }}
  awsAccessKeyId: {{ include "defra-wims.awsAccessKeyId" . | b64enc | quote }}
  awsSecretAccessKey: {{ include "defra-wims.awsSecretAccessKey" . | b64enc | quote }}
  {{- end }}
  {{- with .Values.extraSecret }}
  {{- tpl . $ | nindent 2 }}
  {{- end }}
{{- end }}
