apiVersion: v1
kind: Service
metadata:
  name: {{ include "defra-wims.fullname" . }}-api
  labels:
    app: {{ include "defra-wims.fullname" . }}-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-wims-api
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http-wims-api
  selector:
    app: {{ include "defra-wims.fullname" . }}-api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "defra-wims.fullname" . }}-db
  labels:
    app: {{ include "defra-wims.fullname" . }}-db
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-wims-db
      port: 3030
      protocol: TCP
      targetPort: 3030
  selector:
    app: {{ include "defra-wims.fullname" . }}-db
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "defra-wims.fullname" . }}-ui
  labels:
    app: {{ include "defra-wims.fullname" . }}-ui
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-wims-ui
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: {{ include "defra-wims.fullname" . }}-ui
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "defra-wims.fullname" . }}-varnish
  labels:
    {{- include "defra-wims.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    app: {{ include "defra-wims.fullname" . }}-varnish
