{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "defra-wims.serviceAccountName" . }}
  labels:
    {{- include "defra-wims.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
--- 
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: restart-wims-db-user
  labels:
    app: {{ include "defra-wims.fullname" . }}
    instance: {{ include "defra-wims.fullname" . }}-processor
    role: processor     
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restart-wims-db-role
  labels:
    app: {{ include "defra-wims.fullname" . }}
    instance: {{ include "defra-wims.fullname" . }}-processor
    role: processor    
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    verbs: ["get", "patch", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restart-wims-db-role-binding
  labels:
    app: {{ include "defra-wims.fullname" . }}
    instance: {{ include "defra-wims.fullname" . }}-processor
    role: processor    
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: restart-wims-db-role
subjects:
  - kind: ServiceAccount
    name: restart-wims-db-user
