{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reservoir-flood-maps
  annotations:
    {{- if .Values.ingress.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    {{- end }}
    ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: {{ .Values.metadata.vhost }}
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: {{ tpl .Values.staticApp.target . }}/$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      gzip              on;
      gzip_comp_level   1;
      gzip_min_length   20;
      gzip_http_version 1.1;
      gzip_proxied      any;
      gzip_types        text/css text/plain application/xml application/javascript application/json image/svg+xml;
      gzip_vary         on;
    {{- if .Values.ingress.whitelistSourceRange }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.ingress.whitelistSourceRange }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.pathPrefix }}/metadata.json
            pathType: Prefix
            backend:
              service:
                name: reservoir-flood-maps-metadata
                port:
                  number: 443
{{- end }}
