apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "defra-dsr.fullname" . }}-country-backend
  labels:
    app: {{ include "defra-dsr.fullname" . }}-country-backend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "defra-dsr.fullname" . }}-country-backend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "defra-dsr.fullname" . }}-country-backend
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "defra-dsr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-country-backend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          command: ["java", "-jar", "/srv/openregister-java/openregister-java.jar", "server", "/srv/openregister-java/config/config.yaml"]
          ports:
            - name: backend
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          env:
            - name: REGISTER
              value: country
            - name: FIELDS_JSON
              value: http://{{ include "defra-dsr.fullname" . }}:-field-backend:{{ .Values.backend.service.port }}/records.json
            - name: REGISTER_JSON
              value: http://{{ include "defra-dsr.fullname" . }}-register-backend:{{ .Values.backend.service.port }}/records.json
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /srv/openregister-java/config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "defra-dsr.fullname" . }}
            defaultMode: 0644
            items:
              - key: config.yaml
                path: config.yaml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "defra-dsr.fullname" . }}-country-backend
  labels:
    app: {{ include "defra-dsr.fullname" . }}-country-backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: backend
      protocol: TCP
      name: backend
  selector:
    app: {{ include "defra-dsr.fullname" . }}-country-backend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "defra-dsr.fullname" . }}-country-backend
  labels:
    app: {{ include "defra-dsr.fullname" . }}-country-backend
  {{- with .Values.backend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.backend.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.backend.ingress.tls }}
  tls:
    {{- range .Values.backend.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - country.{{ . }}
        {{- end }}
      secretName: country.{{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.backend.ingress.hosts }}
    - host: country.{{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ include "defra-dsr.fullname" $ }}-country-backend
                port:
                  number: {{ $.Values.backend.service.port }}
          {{- end }}
    {{- end }}