apiVersion: v1
kind: Service
metadata:
  name: {{ include "defra-dsr.fullname" . }}-db
  labels:
    app: {{ include "defra-dsr.fullname" . }}-db
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: db
      protocol: TCP
      name: db
  selector:
    app: {{ include "defra-dsr.fullname" . }}-db
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "defra-dsr.fullname" . }}-register-backend
  labels:
    app: {{ include "defra-dsr.fullname" . }}-register-backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: backend
      protocol: TCP
      name: backend
  selector:
    app: {{ include "defra-dsr.fullname" . }}-register-backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "defra-dsr.fullname" . }}-field-backend
  labels:
    app: {{ include "defra-dsr.fullname" . }}-field-backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: backend
      protocol: TCP
      name: backend
  selector:
    app: {{ include "defra-dsr.fullname" . }}-field-backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "defra-dsr.fullname" . }}-datatype-backend
  labels:
    app: {{ include "defra-dsr.fullname" . }}-datatype-backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: backend
      protocol: TCP
      name: backend
  selector:
    app: {{ include "defra-dsr.fullname" . }}-datatype-backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "defra-dsr.fullname" . }}-frontend-db
  labels:
    app: {{ include "defra-dsr.fullname" . }}-frontend-db
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: db
      protocol: TCP
      name: db
  selector:
    app: {{ include "defra-dsr.fullname" . }}-frontend-db
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "defra-dsr.fullname" . }}-frontend
  labels:
    app: {{ include "defra-dsr.fullname" . }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: frontend
      protocol: TCP
      name: frontend
  selector:
    app: {{ include "defra-dsr.fullname" . }}-frontend    