apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "defra-efde.fullname" . }}-{{ .Values.release }}
  labels:
    app: {{ template "defra-efde.fullname" . }}-{{ .Values.release }}
    chart: {{ template "defra-efde.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- with .Values.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
data:
  default.vcl: |
    vcl 4.0;
    # this points at the ecology reitit api:
    backend default {
        .host = "{{ include "defra-efde.fullname" . }}-api-{{ .Values.release }}";
        .port = "8080";
    }

    sub vcl_recv {
        # Happens before we check if we have this in cache already.
        #
        # Typically you clean up the request here, removing cookies you don't need,
        # rewriting the request, etc.

        # dont cache pingdom checks
        if ( req.http.User-Agent ~ "Pingdom" ) {
          return (pass);
        }

        # dont cache health checks
        if ( req.http.User-Agent ~ "GoogleHC" ) {
          return (pass);
        }

        set req.backend_hint = default;

        # get rid of the cookies and auth as this stops it caching.
        unset req.http.Cookie;
        unset req.http.Authorization;
    }

    sub vcl_backend_response {
        # Happens after we have read the response headers from the backend.
        #
        # Here you clean the response headers, removing silly Set-Cookie headers
        # and other mistakes your backend does.

        # Serve pages from the cache should we get a sudden error and re-check in one sec
        if (beresp.status >= 500) {
          set beresp.grace = 1s;
          set beresp.ttl = 1s;
        } else {
          #otherwise cache for 1 year, with a 12h grace.
          
          /* Remove Expires from backend, it's not long enough */
          unset beresp.http.expires;

          /* Set the clients TTL on this object */
          set beresp.http.cache-control = "max-age=1800";

          /* Set how long Varnish will keep it */
          set beresp.grace = 12h;
          set beresp.ttl = 1y;

          /* marker for vcl_deliver to reset Age: */
          set beresp.http.magicmarker = "1";
          
        }

        return (deliver);
    }

    sub vcl_deliver {
        # Happens when we have all the pieces we need, and are about to send the
        # response to the client.
        #
        # You can do accounting or modifying the final object here.

        if (resp.http.magicmarker) {
                /* Remove the magic marker */
                unset resp.http.magicmarker;

                /* By definition we have a fresh object */
                set resp.http.age = "0";
        }

        # useful for debugging:
        if (obj.hits > 0) {
          set resp.http.X-Varnish-Cache = "HIT";
        }
        else {
          set resp.http.X-Varnish-Cache = "MISS";
        }
    }
  default-shiny.vcl: |
    vcl 4.0;
    # this points at the ecology reitit api:
    backend default {
        .host = "{{ include "defra-efde.fullname" . }}-shiny-{{ .Values.release }}";
        .port = "3838";
    }

    sub vcl_recv {
        # Happens before we check if we have this in cache already.
        #
        # Typically you clean up the request here, removing cookies you don't need,
        # rewriting the request, etc.

        # dont cache pingdom checks
        if ( req.http.User-Agent ~ "Pingdom" ) {
          return (pass);
        }

        # dont cache health checks
        if ( req.http.User-Agent ~ "GoogleHC" ) {
          return (pass);
        }

        set req.backend_hint = default;

        # get rid of the cookies and auth as this stops it caching.
        unset req.http.Cookie;
        unset req.http.Authorization;
    }

    sub vcl_backend_response {
        # Happens after we have read the response headers from the backend.
        #
        # Here you clean the response headers, removing silly Set-Cookie headers
        # and other mistakes your backend does.

        # Serve pages from the cache should we get a sudden error and re-check in one sec
        if (beresp.status >= 500) {
          set beresp.grace = 1s;
          set beresp.ttl = 1s;
        } else {
          #otherwise cache for 1 year, with a 12h grace.
          
          /* Remove Expires from backend, it's not long enough */
          unset beresp.http.expires;

          /* Set the clients TTL on this object */
          set beresp.http.cache-control = "max-age=1800";

          /* Set how long Varnish will keep it */
          set beresp.grace = 12h;
          set beresp.ttl = 1y;

          /* marker for vcl_deliver to reset Age: */
          set beresp.http.magicmarker = "1";
          
        }

        return (deliver);
    }

    sub vcl_deliver {
        # Happens when we have all the pieces we need, and are about to send the
        # response to the client.
        #
        # You can do accounting or modifying the final object here.

        if (resp.http.magicmarker) {
                /* Remove the magic marker */
                unset resp.http.magicmarker;

                /* By definition we have a fresh object */
                set resp.http.age = "0";
        }

        # useful for debugging:
        if (obj.hits > 0) {
          set resp.http.X-Varnish-Cache = "HIT";
        }
        else {
          set resp.http.X-Varnish-Cache = "MISS";
        }
    }    