apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "defra-efde.fullname" . }}
  labels:
    {{- include "defra-efde.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "defra-efde.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "defra-efde.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "defra-efde.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: GDB_ENDPOINT_COLOUR
              value: "green"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "defra-efde.fullname" . }}-shiny
  labels:
    app: {{ include "defra-efde.fullname" . }}-shiny
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "defra-efde.fullname" . }}-shiny
  template:
    metadata:
      labels:
        app: {{ include "defra-efde.fullname" . }}-shiny
    spec:
      containers:
      - name: {{ include "defra-efde.fullname" . }}-shiny
        image: "{{ .Values.shiny.image.repository }}:{{ .Values.shiny.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.shiny.image.pullPolicy }}
        ports:
          - containerPort: 3838
            name: http-shiny
        resources:
          {{- toYaml .Values.shiny.resources | nindent 12 }}
        volumeMounts:
          - name: data
            mountPath: /var/lib/data/csv
            subPath: efde/csv                
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.shiny.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.shiny.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "defra-efde.fullname" . }}-data-blob
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "defra-efde.fullname" . }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "defra-efde.fullname" . }}-db
  strategy:
    type: Recreate
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: {{ include "defra-efde.fullname" . }}-db
    spec:
      containers:
        - image: "{{ .Values.graphdb.image.repository }}:{{ .Values.graphdb.image.tag }}"
          args: ["-XX:MaxRAMPercentage=70", "-Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import"]
          imagePullPolicy: {{ .Values.graphdb.image.pullPolicy }}
          name: {{ include "defra-efde.fullname" . }}-db
          ports:
            - containerPort: 7200
              protocol: TCP
          resources:
            {{- toYaml .Values.graphdb.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/graphdb/dist/logs
              name: graphdb-logs          
            - mountPath: /opt/graphdb/home/graphdb-import
              name: graphdb-import
            - mountPath: /opt/graphdb/dist/data/repositories
              name: graphdb-databases
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      {{- with .Values.graphdb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.graphdb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}      
      volumes:
        - name: graphdb-import
          persistentVolumeClaim:
            claimName: {{ include "defra-efde.fullname" . }}-import
        - name: graphdb-logs
          persistentVolumeClaim:
            claimName: {{ include "defra-efde.fullname" . }}-logs            
        - name: graphdb-databases
          persistentVolumeClaim:
            claimName: {{ include "defra-efde.fullname" . }}-databases            