apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "defra-efde.fullname" . }}-{{ .Values.release }}
  labels:
    {{- include "defra-efde.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "defra-efde.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "defra-efde.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "defra-efde.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: API_ENDPOINT
              value: {{ .Values.graphEndpoint }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "defra-efde.fullname" . }}-shiny-{{ .Values.release }}
  labels:
    app: {{ include "defra-efde.fullname" . }}-shiny-{{ .Values.release }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "defra-efde.fullname" . }}-shiny-{{ .Values.release }}
  template:
    metadata:
      labels:
        app: {{ include "defra-efde.fullname" . }}-shiny-{{ .Values.release }}
    spec:
      containers:
      - name: {{ include "defra-efde.fullname" . }}-shiny
        image: "{{ .Values.shiny.image.repository }}:{{ .Values.shiny.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.shiny.image.pullPolicy }}
        ports:
          - containerPort: 3838
            name: http-shiny
        resources:
          {{- toYaml .Values.shiny.resources | nindent 12 }}
        volumeMounts:
          - name: data
            mountPath: /var/lib/data/csv
            subPath: efde/csv                
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.shiny.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.shiny.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "defra-efde.fullname" . }}-data-blob-{{ .Values.release }}