{{- if .Values.varnish.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "defra-efde.fullname" . }}-varnish-{{ .Values.release }}
  annotations:
    kubernetes.io/ingress.class: nginx    
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/proxy-body-size: '0'
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
  labels:
    app: {{ include "defra-efde.fullname" . }}-varnish-{{ .Values.release }}
spec:
  rules:
  {{- range .Values.varnish.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      - backend:
          service: 
            name: {{ include "defra-efde.fullname" $ }}-varnish-{{ $.Values.release }}
            port: 
              number: 80
        path: /ecology/api(/|$)(.*)
        pathType: Prefix
  {{- end }}
  {{- if .Values.varnish.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.varnish.ingress.hosts }}
        - {{ .host }}
        {{- end }}
      secretName: {{ include "defra-efde.fullname" . }}-varnish-tls
  {{- end }}
{{- end }}
---
{{- if .Values.shiny.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "defra-efde.fullname" . }}-shiny-{{ .Values.release }}
  annotations:
    kubernetes.io/ingress.class: nginx    
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/proxy-body-size: '0'
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
  labels:
    app: {{ include "defra-efde.fullname" . }}-shiny-{{ .Values.release }}
spec:
  rules:
  {{- range .Values.shiny.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      - backend:
          service: 
            name: {{ include "defra-efde.fullname" $ }}-varnish-shiny-{{ $.Values.release }}
            port: 
              number: 80
        path: /ecology/shiny/
        pathType: Prefix
  {{- end }}
  {{- if .Values.shiny.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.shiny.ingress.hosts }}
        - {{ .host }}
        {{- end }}
      secretName: {{ include "defra-efde.fullname" . }}-shiny-tls
  {{- end }}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: dsptpzbuildartefacts.z33.web.core.windows.net
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /tags/ecology-fish-data-explorer/{{ .Values.explorer.version | default .Chart.AppVersion }}/$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/ecology/explorer)$ $1/ redirect;
      gzip              on;
      gzip_comp_level   1;
      gzip_min_length   20;
      gzip_http_version 1.1;
      gzip_proxied      any;
      gzip_types        text/css text/plain application/xml application/javascript application/json image/svg+xml;
      gzip_vary         on;
  name: {{ include "defra-efde.fullname" . }}-explorer-{{ .Values.release }}
spec:
  rules:
  {{- range .Values.shiny.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      - backend:
          service: 
            name: {{ include "defra-efde.fullname" $ }}-explorer-{{ $.Values.release }}
            port: 
              number: 443
        path: /ecology/explorer(/|$)(.*)
        pathType: Prefix
  {{- end }}
