---
{{- if .Values.shiny.data.storageClassname }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "defra-efde.fullname" . }}-data-blob-{{ .Values.release }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.shiny.data.size }}
  storageClassName: {{ .Values.shiny.data.storageClassname }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "defra-efde.fullname" . }}-logs-{{ .Values.release }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: {{ .Values.graphdb.storageClassName }}
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "defra-efde.fullname" . }}-databases-{{ .Values.release }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: {{ .Values.graphdb.storageClassName }}
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "defra-efde.fullname" . }}-import-{{ .Values.release }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: {{ .Values.graphdb.import.storageClassName }}
  volumeMode: Filesystem    