apiVersion: v1
kind: Service
metadata:
  name: {{ include "defra-efde.fullname" . }}
  labels:
    {{- include "defra-efde.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "defra-efde.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shinyimg
  name: shiny-service
spec:
  ports:
    - name: http-shiny
      port: 80
      protocol: TCP
      targetPort: http-shiny
  selector:
    app: shinyimg
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: defra-efde-explorer
spec:
  type: ExternalName
  externalName: dsptpzbuildartefacts.z33.web.core.windows.net
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: defra-efde-db
  name: defra-efde-db
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 7200
      protocol: TCP
      targetPort: 7200
  selector:
    app: defra-efde-db
  sessionAffinity: None
  type: ClusterIP