apiVersion: v1
kind: Service
metadata:
  name: {{ include "defra-efde.fullname" . }}-{{ .Values.release }}
  labels:
    {{- include "defra-efde.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "defra-efde.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "defra-efde.fullname" . }}-shiny-{{ .Values.release }}
  name: {{ include "defra-efde.fullname" . }}-shiny-{{ .Values.release }}
spec:
  ports:
    - name: http-shiny
      port: 80
      protocol: TCP
      targetPort: http-shiny
  selector:
    app: {{ include "defra-efde.fullname" . }}-shiny-{{ .Values.release }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "defra-efde.fullname" . }}-explorer-{{ .Values.release }}
spec:
  type: ExternalName
  externalName: dsptpzbuildartefacts.z33.web.core.windows.net
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "defra-efde.fullname" . }}-db-{{ .Values.release }}
  name: {{ include "defra-efde.fullname" . }}-db-{{ .Values.release }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 7200
      protocol: TCP
      targetPort: 7200
  selector:
    app: {{ include "defra-efde.fullname" . }}-db-{{ .Values.release }}
  sessionAffinity: None
  type: ClusterIP