apiVersion: v1
kind: Service
metadata:
  name: {{ include "defra-efde.fullname" . }}-varnish-{{ .Values.release }}
  labels:
    {{- include "defra-efde.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
  selector:
    app: {{ include "defra-efde.fullname" . }}-varnish-{{ .Values.release }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "defra-efde.fullname" . }}-api-{{ .Values.release }}
  labels:
    app: {{ include "defra-efde.fullname" . }}-api-{{ .Values.release }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ include "defra-efde.fullname" . }}-api-{{ .Values.release }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "defra-efde.fullname" . }}-shiny-{{ .Values.release }}
  name: {{ include "defra-efde.fullname" . }}-shiny-{{ .Values.release }}
spec:
  ports:
    - name: http-shiny
      port: 80
      protocol: TCP
      targetPort: http-shiny
  selector:
    app: {{ include "defra-efde.fullname" . }}-shiny-{{ .Values.release }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "defra-efde.fullname" . }}-explorer-{{ .Values.release }}
spec:
  type: ExternalName
  externalName: dsptpzbuildartefacts.z33.web.core.windows.net