apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "marine-plans-explorer.fullname" . }}-cm
  labels:
    app: {{ template "marine-plans-explorer.fullname" . }}
    chart: {{ template "marine-plans-explorer.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- with .Values.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
data:
  contactUrl: {{ .Values.contactUrl }}
  marinePlanningDocumentsUrl: {{ .Values.marinePlanningDocumentsUrl }}
  init-mongo.sh: |
    #!/bin/bash
    until mongosh --eval "db.adminCommand('ping')"
      do sleep 1
    done
    set -e
    echo Using database $MONGO_INITDB_DATABASE
    touch /testfilefrom.sh
    mongosh <<EOF
    use $MONGO_INITDB_DATABASE

    db.createUser({
        user:'$MONGO_INITDB_ROOT_USERNAME',
        pwd: '$MONGO_INITDB_ROOT_PASSWORD',
        roles:[{
            role:'readWrite',
            db: '$MONGO_INITDB_DATABASE'
        }]
    })
    EOF
  {{- with .Values.extraConfigMap }}
  {{- tpl . $ | nindent 2 }}
  {{- end }}
